### ISSUE TITLE
[FEAT] 아이템 구매 기능

### ISSUE THREAD

**Issue by seoyeon22** [UMC-Focus-Up/FocusUp-BE#10]
## 🔥 Feature Issue
아이템 구매 api

## ✅ TODO
 - [x] 포인트 계산
 - [x] 구매 기록 추가
 - [x] 생명권 구매 및 사용
 - [x] 아이템 중복 구매 방지
