### ISSUE TITLE
[FEAT] 홈, 캐릭터 화면 조회 기능

### ISSUE THREAD

**Issue by seoyeon22** [UMC-Focus-Up/FocusUp-BE#16]
## 🔥 Feature Issue
홈 조회 api, 캐릭터 화면 조회 api

## ✅ TODO
 - [x] 유저 정보 조회
 - [x] 현재 또는 다음에 해야하는 루틴 조회
 - [x] 현재 장착하고 있는 아이템 조회
