### ISSUE TITLE
[FEAT] Dockerfile, CI/CD 구축

### ISSUE THREAD

**Issue by bianbbc87** [UMC-Focus-Up/FocusUp-BE#2]
## 🔥 Feature Issue
Dockerfile을 이용한 CI/CD 구축

## ✅ TODO
 - [x] 스프링부트 도커 파일 빌드
 - [x] EC2 생성
 - [x] mysql 도커 파일 생성
 - [x] test용 api 생성
 - [x] CI/CD yml 파일 생성 및 테스트
