### ISSUE TITLE
[FEAT] 루틴 기능

### ISSUE THREAD

**Issue by bianbbc87** [UMC-Focus-Up/FocusUp-BE#5]
## 🔥 Feature Issue
루틴에 대한 기능 개발

## ✅ TODO
 - [ ] 루틴 완료하기
 - [ ] 목표 루틴 조회
 - [ ] 목표 루틴 생성
 - [ ] 목표 루틴 삭제
