### ISSUE TITLE
[BUG] 레벨 로직 수정 및 레벨 조회 기능 수정

### ISSUE THREAD

**Issue by munjji** [UMC-Focus-Up/FocusUp-BE#57]
## 🔥 Fix Issue
레벨 로직 수정 및 레벨 조회 기능 수정

## ✅ TODO
 - [x] 레벨 로직 수정
 - [x] 레벨 조회 기능 수정 (마이페이지, 홈)
 - [x] 레벨 변경 시, 변경하고자 하는 newlevel의 값이 현재 level 보다 클 경우 예외 처리 추가
